steps:
  - label: ":shipit: default build"
    commands:
      - ./scripts/bootstrap
      - ./scripts/cibuild build
      - ./scripts/cibuild container
    agents:
      container_image: ubuntu-2104-ci
