steps:
  - label: ":shipit: default build"
    commands:
      - ./scripts/bootstrap
      - ./scripts/cibuild build
      - TEST_FAST=true ./scripts/test
    agents:
      container_image: ubuntu-2110-ci
