#!/bin/bash

set -e -o pipefail

usage() {
  cmd_help
  exit 1
}

cmd_help () {
  echo 'valid args: build, debug, help'
  echo ""
}


BASE_PACKAGE="github.com/greymatter-io/lxdk"
VERSIONS_PACKAGE="${BASE_PACKAGE}/version"
MAIN_PACKAGE="${BASE_PACKAGE}/cmd/lxdk"
COMMIT=$(git rev-parse --verify --short HEAD 2> /dev/null || echo "UNKNOWN")
COMMIT_FLAG="-X '${VERSIONS_PACKAGE}.commit=$COMMIT'"
VERSION_FLAG="-X '${VERSIONS_PACKAGE}.version=$VERSION'"

cmd_build() {
  CGO_ENABLED=0 GOOS=$goos go build \
         -o "./bin/lxdk" -a \
         -ldflags "-extldflags \"-static\" $COMMIT_FLAG $VERSION_FLAG" \
         --mod=vendor $MAIN_PACKAGE
}

cmd_debug () {
  go build -o ./bin/lxdk \
      -ldflags "$VERSION_FLAG $COMMIT_FLAG" \
      --mod=vendor \
      -gcflags 'all=-N -l' "$MAIN_PACKAGE"
}

if [ $# -eq "0" ]; then
    cmd_build
    exit 0
fi
CMD=$1
case $CMD in
build|debug|help)
  shift
  cmd_$CMD
  ;;
*)
  echo "invalid argument: $1"
  exit 1
  ;;
esac
